# Site settings
title: Little Apple Daycare
email: littleAppleDaycare88@gmail.com
description: Little Apple Daycare in Saugus, Massachusetts is a bilingual Mandarin and English learning center
baseurl: ""
url: "http://littleapple-daycare.com"

author:
  email    : littleAppleDaycare88@gmail.com
  url      : http://littleapple-daycare.com
  facebook : 
  twitter  :

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
